package com.wreckingballsoftware.blackmailed.ui.gameplay.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class GameplayState(
    val timeRemaining: String = "2:00",
    val prompt: String = "Describe the day in the life of a forgetful wedding planner trying to organize a wedding with the help of their equally forgetful assistant.",
    val blackmailLetter: List<String> = emptyList(),
    val blackmailTray: List<String> = listOf(
        "I",
        "always",
        "am",
        "art",
        "away",
        "bad",
        "bank",
        "beam",
        "bear",
        "board",
        "bomb",
        "brain",
        "bulbous",
        "buy",
        "chaos",
        "check",
        "collect",
        "compete",
        "could",
        "crowd",
        "crush",
        "curious",
        "dangerous",
        "dark",
        "decide",
        "decrease",
        "did",
        "don't",
        "drip",
        "excite",
        "fiend",
        "gigantic",
        "give",
        "grip",
        "heart",
        "illness",
        "insult",
        "jerk",
        "joke",
        "let",
        "liar",
        "lucky",
        "ly",
        "mingle",
        "my",
        "object",
        "person",
        "ping",
        "please",
        "queen",
        "righteous",
        "she",
        "shine",
        "so",
        "spooky",
        "squeeze",
        "stress",
        "sweet",
        "territory",
        "tip",
        "too",
        "tough",
        "treasure",
        "vacation",
        "was",
        "wear",
        "weird",
        "where",
        "woman",
        "wreck",
    ),
) : Parcelable
